-------------------- COMMON DOMAINS ----------------------------
CREATE DOMAIN t_boolean AS CHARACTER(1);
CREATE DOMAIN t_flag AS BOOLEAN DEFAULT FALSE;

-- Codes
CREATE DOMAIN t_code AS CHARACTER VARYING(20);
CREATE DOMAIN t_code1 AS CHARACTER(1);
CREATE DOMAIN t_code2 AS CHARACTER(2);
CREATE DOMAIN t_code3 AS CHARACTER(3);
CREATE DOMAIN t_code4 AS CHARACTER VARYING(4);
CREATE DOMAIN t_code6 AS CHARACTER VARYING(6);

-- Dates
CREATE DOMAIN t_datetime AS DATE;
CREATE DOMAIN t_time AS TIME WITHOUT TIME ZONE;
CREATE DOMAIN t_timestamp AS TIMESTAMP WITH TIME ZONE DEFAULT now();
CREATE DOMAIN t_timestamp_effective AS TIMESTAMP WITH TIME ZONE DEFAULT now();
CREATE DOMAIN t_timestamp_expiration AS TIMESTAMP WITH TIME ZONE;
CREATE DOMAIN t_timestampz AS TIMESTAMP WITH TIME ZONE;
CREATE DOMAIN t_timezone_offset AS CHARACTER VARYING(5);

-- Calendar
CREATE DOMAIN t_date_identity AS INTEGER;
CREATE DOMAIN t_date_calendar AS DATE;
CREATE DOMAIN t_date_calendar_day AS SMALLINT CHECK (value BETWEEN 1 AND 31);
CREATE DOMAIN t_date_calendar_day_of_month AS SMALLINT CHECK (value BETWEEN 1 AND 31);
CREATE DOMAIN t_date_calendar_day_of_qtr AS SMALLINT CHECK (value BETWEEN 1 AND 94);
CREATE DOMAIN t_date_calendar_month AS SMALLINT CHECK ( value BETWEEN 1 AND 12);
CREATE DOMAIN t_date_calendar_month_of_quarter AS SMALLINT CHECK ( value BETWEEN 1 AND 3);
CREATE DOMAIN t_date_calendar_week AS SMALLINT CHECK ( value BETWEEN 1 AND 53);
CREATE DOMAIN t_date_calendar_week_of_month AS SMALLINT CHECK ( value BETWEEN 1 AND 5);
CREATE DOMAIN t_date_calendar_week_of_qtr AS SMALLINT CHECK ( value BETWEEN 1 AND 15);
CREATE DOMAIN t_date_calendar_weekday AS SMALLINT CHECK ( value BETWEEN 1 AND 7);
CREATE DOMAIN t_date_calendar_year AS SMALLINT CHECK ( value BETWEEN 1900 AND 2100);
CREATE DOMAIN t_date_calendar_year_day AS SMALLINT CHECK ( value BETWEEN 1 AND 366);
CREATE DOMAIN t_date_fiscal AS NUMERIC(7, 0);
CREATE DOMAIN t_date_fiscal_day AS SMALLINT CHECK ( value BETWEEN 1 AND 31);
CREATE DOMAIN t_date_fiscal_month AS SMALLINT CHECK ( value BETWEEN 1 AND 12);
CREATE DOMAIN t_date_fiscal_quarter AS SMALLINT CHECK (value BETWEEN 1 AND 4);
CREATE DOMAIN t_date_fiscal_week AS SMALLINT CHECK ( value BETWEEN 1 AND 53);

-- Text
CREATE DOMAIN t_table_name AS CHARACTER VARYING(63);
CREATE DOMAIN t_description AS CHARACTER VARYING;
CREATE DOMAIN t_description_short AS CHARACTER VARYING(255);
CREATE DOMAIN t_password AS CHARACTER VARYING(255);
CREATE DOMAIN t_name AS CHARACTER VARYING(128);
CREATE DOMAIN t_text AS CHARACTER VARYING;

-- Numbers
CREATE DOMAIN t_count AS INTEGER DEFAULT 0;
CREATE DOMAIN t_short_count AS SMALLINT DEFAULT 0;
CREATE DOMAIN t_quantity AS NUMERIC;
CREATE DOMAIN t_exchange_rate AS NUMERIC;
CREATE DOMAIN t_float AS DOUBLE PRECISION;
CREATE DOMAIN t_fraction AS DOUBLE PRECISION;
CREATE DOMAIN t_hexint AS BIGINT DEFAULT 0;
CREATE DOMAIN t_line_number AS SMALLINT;
CREATE DOMAIN t_money AS NUMERIC DEFAULT 0;
CREATE DOMAIN t_percent AS DOUBLE PRECISION;

-- Ids
CREATE DOMAIN t_identity AS BIGINT;
CREATE DOMAIN t_identity_alphanumeric AS CHARACTER VARYING(20);
CREATE DOMAIN t_ipaddress AS CHARACTER VARYING(15);
CREATE DOMAIN t_isbn AS CHARACTER VARYING(13);
CREATE DOMAIN t_issn AS CHARACTER VARYING(9);
CREATE DOMAIN t_uuid AS UUID DEFAULT gen_random_uuid();

-- json
CREATE DOMAIN t_json AS JSONB;
